  CREATE TABLE "AA_EXEMPTED_EMP" 
   (	"AA_EXEMPTED_EMP_ID" NUMBER, 
	"EMP_EMAIL" VARCHAR2(200 CHAR), 
	"CREATED_BY" VARCHAR2(200 CHAR), 
	"CREATED_ON" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(200 CHAR), 
	"UPDATED_ON" TIMESTAMP (6), 
	"COMMENTS" VARCHAR2(2000 CHAR), 
	 CONSTRAINT "AA_EXEMPTED_EMP_PK" PRIMARY KEY ("EMP_EMAIL")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "AA_EXEMPTED_EMP" ADD CONSTRAINT "AA_EXEMPTED_EMP_EMAIL_FK" FOREIGN KEY ("EMP_EMAIL")
	  REFERENCES "AA_EMPLOYEES" ("EMP_EMAIL") ENABLE;